imageTag: "v2.26.0"
#crds are installed in the k8s apply step
crd:
  present: true
ingress:
  enabled: true
  annotations:
   cert-manager.io/issuer: letsencrypt-prod

  tls:
  - secretName: dex-tls
    hosts:
    - dex.example.com
  hosts:
  - host: dex.example.com
    paths:
    - path: /

# https termination by ingress instead of through dex
https:
  enabled: false
volumeMounts:
- mountPath: /etc/dex/google
  name: google-sa
volumes:
- name: google-sa
  secret:
    secretName: google-sa
config:
  issuer: https://dex.example.com
  storage:
    type: kubernetes
    config:
      inCluster: true
  connectors:
  - type: google
    id: google
    name: Google
    config:
      # Connector config values starting with a "$" will read from the environment.
      clientID: <client - id >
      clientSecret: <client - secret>
      # Dex's issuer URL + "/callback"
      redirectURI: https://dex.example.com/callback
      # Google supports whitelisting allowed domains when using G Suite
      # (Google Apps). The following field can be set to a list of domains
      # that can log in:
      #
      hostedDomains:
        - example.com
      groups:
        - admin@example.com
        - dev@example.com
      serviceAccountFilePath: /etc/dex/google/sa.json
      adminEmail: <put admin email here >
  staticClients:
    - id: kubelogin
      name: 'Kubernetes CLI'
      secret: dex-test
      redirectURIs:
      - http://localhost:8000
      - http://localhost:8080/oauth2/callback
